Suniland\ComunBundle\Entity\Galerias:
    type: entity
    table: galerias
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: AUTO
    fields:
        titulo:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
        imagen:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
        activa:
            type: boolean
            nullable: true
    lifecycleCallbacks: {  }
